// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseDevOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcH1QWReSVMTIdMecRQbWZjw1EIMlcemQ',
    appId: '1:769978264075:web:0c14083fe72f1624da350e',
    messagingSenderId: '769978264075',
    projectId: 'ilurama',
    authDomain: 'ilurama.firebaseapp.com',
    storageBucket: 'ilurama.appspot.com',
    measurementId: 'G-M7X25XRND5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRVj78kAJ0pHizDmAeZdH6dXnc6NxE6yY',
    appId: '1:769978264075:android:8f1ea4551fc6a582da350e',
    messagingSenderId: '769978264075',
    projectId: 'ilurama',
    storageBucket: 'ilurama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAawbWaJ07yvBtg2mj3_DEjgGT2np1bDBQ',
    appId: '1:769978264075:ios:4907906f8c45cd6eda350e',
    messagingSenderId: '769978264075',
    projectId: 'ilurama',
    storageBucket: 'ilurama.appspot.com',
    androidClientId: '769978264075-p3011obub926uhhpfq8tllr73ic95dqi.apps.googleusercontent.com',
    iosClientId: '769978264075-ainqr2g5pgtr48no0sksc8rhl9vhgtq3.apps.googleusercontent.com',
    iosBundleId: 'com.misfitcoders.ilurama',
  );
}
